name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
   # - run: npm test
    - run: npm run deploy:ci --if-present

      env:
        CI: true
        GITHUB_TOKEN : ${{ secrets.G_T}}
        ## APP: ${{env.APP}}				 
        # Deploy env
        # HOST: ${{ secrets.HOST }}
        # PASS: ${{ secrets.PASS }}
        # USER: ${{ secrets.USER }}